export enum ObjectDescriptor {
  edible = 1,
  drinkable = 2,
  poisoned = 3,
  weapon = 4,
  building_material = 5,
  regenerative = 6,
  fruit_tree = 7,
  apple = 8,
  pear = 9,
  in_season = 10,
  willow_tree = 11,
  walnut_tree = 12,
  wood_shack = 13,
  home = 14,
}
